mini-project: add.o sub.o mul.o div.o main.o
	${CC} add.o sub.o mul.o div.o main.o -o mini-project

add.o : add.c
	${CC} -c -o add.o add.c

sub.o : sub.c
	${CC} -c -o sub.o sub.c

mul.o : mul.c
	${CC} -c -o mul.o mul.c

div.o : div.c
	${CC} -c -o div.o div.c

main.o : main.c
	${CC} -c -o main.o main.c
